In [1]:
# Import pandas to handle data in tables (like Excel spreadsheets)
import pandas as pd

# Import numpy to perform fast mathematical operations on lists of numbers
import numpy as np 

# Import matplotlib to create graphs, charts, and visual plots
import matplotlib.pyplot as plt

In [2]:
# Loads the data file (CSV) and stores it in a table called 'unemployment'
unempoyment = pd.read_csv('/workspaces/Machine-Learning-6-SIN-A-Mar-Jul-2026/data/country_total.csv')

In [3]:
# Checks the data type of the variable to see what it is
type(unempoyment)

pandas.DataFrame

In [4]:
# Shows the first 5 rows of the data to get a quick preview
unempoyment.head()

  country seasonality    month  unemployment  unemployment_rate
0      at         nsa  1993.01        171000                4.5
1      at         nsa  1993.02        175000                4.6
2      at         nsa  1993.03        166000                4.4
3      at         nsa  1993.04        157000                4.1
4      at         nsa  1993.05        147000                3.9

In [5]:
# Returns the dimensions of the table (number of rows and columns)
unempoyment.shape

(20796, 5)

In [6]:
# Lists the names of all the columns (headers) in the table
unempoyment.columns

Index(['country', 'seasonality', 'month', 'unemployment', 'unemployment_rate'], dtype='str')

In [7]:
# Shows the data type of every column (e.g., numbers or text)
unempoyment.dtypes

country                  str
seasonality              str
month                float64
unemployment           int64
unemployment_rate    float64
dtype: object

In [8]:
# Shows a statistical summary of the data (mean, min, max, etc.)
unempoyment.describe()

              month  unemployment  unemployment_rate
count  20796.000000  2.079600e+04       19851.000000
mean    1999.401290  7.900818e+05           8.179764
std        7.483751  1.015280e+06           3.922533
min     1983.010000  2.000000e+03           1.100000
25%     1994.090000  1.400000e+05           5.200000
50%     2001.010000  3.100000e+05           7.600000
75%     2006.010000  1.262250e+06          10.000000
max     2010.120000  4.773000e+06          20.900000