In [1]:
# Import pandas to handle data in tables (like Excel spreadsheets)
import pandas as pd

# Import numpy to perform fast mathematical operations on lists of numbers
import numpy as np 

# Import matplotlib to create graphs, charts, and visual plots
import matplotlib.pyplot as plt

In [2]:
# Loads the data file (CSV) and stores it in a table called 'unemployment'
unempoyment = pd.read_csv('/workspaces/Machine-Learning-6-SIN-A-Mar-Jul-2026/data/country_total.csv')

In [3]:
# Checks the data type of the variable to see what it is
type(unempoyment)

pandas.DataFrame

In [4]:
# Shows the first 5 rows of the data to get a quick preview
unempoyment.head()

  country seasonality    month  unemployment  unemployment_rate
0      at         nsa  1993.01        171000                4.5
1      at         nsa  1993.02        175000                4.6
2      at         nsa  1993.03        166000                4.4
3      at         nsa  1993.04        157000                4.1
4      at         nsa  1993.05        147000                3.9

In [5]:
# Returns the dimensions of the table (number of rows and columns)
unempoyment.shape

(20796, 5)

In [6]:
# Lists the names of all the columns (headers) in the table
unempoyment.columns

Index(['country', 'seasonality', 'month', 'unemployment', 'unemployment_rate'], dtype='str')

In [7]:
# Shows the data type of every column (e.g., numbers or text)
unempoyment.dtypes

country                  str
seasonality              str
month                float64
unemployment           int64
unemployment_rate    float64
dtype: object

In [8]:
# Shows a statistical summary of the data (mean, min, max, etc.)
unempoyment.describe()

              month  unemployment  unemployment_rate
count  20796.000000  2.079600e+04       19851.000000
mean    1999.401290  7.900818e+05           8.179764
std        7.483751  1.015280e+06           3.922533
min     1983.010000  2.000000e+03           1.100000
25%     1994.090000  1.400000e+05           5.200000
50%     2001.010000  3.100000e+05           7.600000
75%     2006.010000  1.262250e+06          10.000000
max     2010.120000  4.773000e+06          20.900000

In [9]:
# Creates a list of characters stored in a variable called 'my_list'
my_list = ['a', 'b', 'c', 'd', 'e', 'f']

In [10]:
# Gets all items from the 3rd element to the very end
my_list[2:]

['c', 'd', 'e', 'f']

In [11]:
# Gets all items from the 3rd element to the very end
my_list[len(my_list)-4:]

['c', 'd', 'e', 'f']

In [14]:
# new dataset countries.csv
dataset = pd.read_csv('/workspaces/Machine-Learning-6-SIN-A-Mar-Jul-2026/data/countries.csv')

In [16]:
dataset.head()

dataset.sample(5)

dataset.info()

dataset.shape

dataset['country_group'].value_counts()

dataset.describe()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              30 non-null     str
 1   google_country_code  30 non-null     str
 2   country_group        30 non-null     str
 3   name_en              30 non-null     str
 4   name_fr              30 non-null     str
 5   name_de              30 non-null     str
 6   latitude             30 non-null     float64
 7   longitude            30 non-null     float64
dtypes: float64(2), str(6)
memory usage: 2.0 KB

        latitude  longitude
count  30.000000  30.000000
mean   49.092609  14.324579
std     7.956624  11.257010
min    35.129141  -8.239122
25%    43.230916   6.979186
50%    49.238087  14.941462
75%    54.090400  23.351690
max    64.950159  35.439795

In [17]:
# Gets the value at row 3 for that specific column
dataset.loc[3, 'google_country_code']

'HR'

In [18]:
# Gets the first 5 rows (index 0 to 4) and all columns
dataset.loc[:4,:]

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
0,at,AT,eu,Austria,Autriche,Österreich,47.696554,13.345980
1,be,BE,eu,Belgium,Belgique,Belgien,50.501045,4.476674
2,bg,BG,eu,Bulgaria,Bulgarie,Bulgarien,42.725674,25.482322
3,hr,HR,non-eu,Croatia,Croatie,Kroatien,44.746643,15.340844
4,cy,CY,eu,Cyprus,Chypre,Zypern,35.129141,33.428682

In [19]:
# Gets all rows and the first 4 columns
dataset.iloc[:,:4]

,country,google_country_code,country_group,name_en
0,at,AT,eu,Austria
1,be,BE,eu,Belgium
2,bg,BG,eu,Bulgaria
3,hr,HR,non-eu,Croatia
4,cy,CY,eu,Cyprus
5,cz,CZ,eu,Czech Republic
6,dk,DK,eu,Denmark
7,ee,EE,eu,Estonia
8,fi,FI,eu,Finland
9,fr,FR,eu,France
10,de,DE,eu,Germany (including former GDR from 1991)
11,gr,GR,eu,Greece
12,hu,HU,eu,Hungary
13,ie,IE,eu,Ireland
14,it,IT,eu,Italy
15,lv,LV,eu,Latvia
16,lt,LT,eu,Lithuania
17,lu,LU,eu,Luxembourg
18,mt,MT,eu,Malta
19,nl,NL,eu,Netherlands
20,no,NO,non-eu,Norway
21,pl,PL,eu,Poland
22,pt,PT,eu,Portugal
23,ro,RO,eu,Romania
24,sk,SK,eu,Slovakia
25,si,SI,eu,Slovenia
26,es,ES,eu,Spain
27,se,SE,eu,Sweden
28,tr,TR,non-eu,Turkey
29,uk,GB,eu,United Kingdom

In [20]:
# Creates a new variable 'test' with rows 20 to 25 and all columns
test = dataset.loc[20:25, :]
test

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
20,no,NO,non-eu,Norway,Norvège,Norwegen,64.556460,12.665766
21,pl,PL,eu,Poland,Pologne,Polen,51.918907,19.134334
22,pt,PT,eu,Portugal,Portugal,Portugal,39.558069,-7.844941
23,ro,RO,eu,Romania,Roumanie,Rumänien,45.942611,24.990152
24,sk,SK,eu,Slovakia,Slovaquie,Slowakei,48.672644,19.700032
25,si,SI,eu,Slovenia,Slovénie,Slowenien,46.149259,14.986617

In [21]:
# Filters the table to show only rows where the country group is 'non-eu'
test[test['country_group'] == 'non-eu']

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
20,no,NO,non-eu,Norway,Norvège,Norwegen,64.55646,12.665766

In [22]:
# Filters the table to show only countries with a longitude greater than 25
dataset[dataset['longitude']>25]

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
2,bg,BG,eu,Bulgaria,Bulgarie,Bulgarien,42.725674,25.482322
4,cy,CY,eu,Cyprus,Chypre,Zypern,35.129141,33.428682
7,ee,EE,eu,Estonia,Estonie,Estland,58.592469,25.806950
8,fi,FI,eu,Finland,Finlande,Finnland,64.950159,26.067564
28,tr,TR,non-eu,Turkey,Turquie,Türkei,38.952942,35.439795